language: java
jdk:
  - oraclejdk6
env: DISPLAY=:99.0
env: GRIFFON_OPTS="-XX:MaxPermSize=250m -Xmx768m"
script: ./griffonw -non-interactive -Dgriffon.artifact.force.upgrade=true test-app;./griffonw -non-interactive -Dgriffon.artifact.force.upgrade=true package-plugin
after_script:
  - test -f ./target/package/griffon-liquibase-*.zip
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: /bin/true